### ISSUE TITLE
Run Modules only client side

### ISSUE THREAD

**Issue by siddarthvader** [mvlabs/isomorphic-mithril#1]
I am using this application architecture in my app but in some places I need to run a module only on client side, is it possible?

P.S: I want to use aws-amplify but since it does not run in NODE env, it breaks the app.

**Comment by ACXgit** [comment]
Hi, I hope it's not too late for an useful reply. [This is an example](https://github.com/mvlabs/isomorphic-mithril/blob/f5fdd3e443c2f2547d3398ce1a80ddbc38f80b01/app/components/SectionContent.js#L3) of a module which is only required client side (it would throw error on the server otherwise).

**Comment by siddarthvader** [comment]
Hi, No you are not. This seems neat and simple. Thanks man.
